//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Reflection;

namespace CodeAlignFix
{
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources
    {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources()
        {
        }

        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager
        {
            get
            {
                if (object.ReferenceEquals(resourceMan, null))
                {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CodeAlignFix.Resources", typeof(Resources).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture
        {
            get
            {
                return resourceCulture;
            }
            set
            {
                resourceCulture = value;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Align assignment operators.
        /// </summary>
        internal static string AssignmentAlignmentTitle
        {
            get
            {
                return ResourceManager.GetString("AssignmentAlignmentTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Consecutive assignments can be aligned.
        /// </summary>
        internal static string AssignmentAlignmentMessageFormat
        {
            get
            {
                return ResourceManager.GetString("AssignmentAlignmentMessageFormat", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Aligns assignment operators in consecutive variable declarations and field assignments..
        /// </summary>
        internal static string AssignmentAlignmentDescription
        {
            get
            {
                return ResourceManager.GetString("AssignmentAlignmentDescription", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Align object initializer properties.
        /// </summary>
        internal static string ObjectInitializerAlignmentTitle
        {
            get
            {
                return ResourceManager.GetString("ObjectInitializerAlignmentTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Object initializer properties can be aligned.
        /// </summary>
        internal static string ObjectInitializerAlignmentMessageFormat
        {
            get
            {
                return ResourceManager.GetString("ObjectInitializerAlignmentMessageFormat", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Aligns assignment operators in object initializer expressions..
        /// </summary>
        internal static string ObjectInitializerAlignmentDescription
        {
            get
            {
                return ResourceManager.GetString("ObjectInitializerAlignmentDescription", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Align method parameters.
        /// </summary>
        internal static string ParameterAlignmentTitle
        {
            get
            {
                return ResourceManager.GetString("ParameterAlignmentTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Method parameters should be aligned (one per line).
        /// </summary>
        internal static string ParameterAlignmentMessageFormat
        {
            get
            {
                return ResourceManager.GetString("ParameterAlignmentMessageFormat", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Ensures method and constructor parameters are placed on separate lines when count exceeds threshold..
        /// </summary>
        internal static string ParameterAlignmentDescription
        {
            get
            {
                return ResourceManager.GetString("ParameterAlignmentDescription", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Align method arguments.
        /// </summary>
        internal static string ArgumentAlignmentTitle
        {
            get
            {
                return ResourceManager.GetString("ArgumentAlignmentTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Method arguments should be aligned (one per line).
        /// </summary>
        internal static string ArgumentAlignmentMessageFormat
        {
            get
            {
                return ResourceManager.GetString("ArgumentAlignmentMessageFormat", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Ensures method invocation arguments are placed on separate lines when count exceeds threshold..
        /// </summary>
        internal static string ArgumentAlignmentDescription
        {
            get
            {
                return ResourceManager.GetString("ArgumentAlignmentDescription", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Align chained method calls.
        /// </summary>
        internal static string ChainedMethodAlignmentTitle
        {
            get
            {
                return ResourceManager.GetString("ChainedMethodAlignmentTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Chained method calls should be on separate lines.
        /// </summary>
        internal static string ChainedMethodAlignmentMessageFormat
        {
            get
            {
                return ResourceManager.GetString("ChainedMethodAlignmentMessageFormat", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Ensures chained method calls are placed on separate lines with proper indentation..
        /// </summary>
        internal static string ChainedMethodAlignmentDescription
        {
            get
            {
                return ResourceManager.GetString("ChainedMethodAlignmentDescription", resourceCulture);
            }
        }
    }
}
