//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CodeAlign {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CodeAlign.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alignment.
        /// </summary>
        internal static string CategoryAlignment {
            get {
                return ResourceManager.GetString("CategoryAlignment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General.
        /// </summary>
        internal static string CategoryGeneral {
            get {
                return ResourceManager.GetString("CategoryGeneral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameters.
        /// </summary>
        internal static string CategoryParameters {
            get {
                return ResourceManager.GetString("CategoryParameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimum number of constructor parameters required before aligning them on separate lines..
        /// </summary>
        internal static string ConstructorThresholdDescription {
            get {
                return ResourceManager.GetString("ConstructorThresholdDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Constructor Parameter Threshold.
        /// </summary>
        internal static string ConstructorThresholdDisplayName {
            get {
                return ResourceManager.GetString("ConstructorThresholdDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Controls whether the plugin is active.
        /// </summary>
        internal static string EnablePluginDescription {
            get {
                return ResourceManager.GetString("EnablePluginDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable Plugin.
        /// </summary>
        internal static string EnablePluginDisplayName {
            get {
                return ResourceManager.GetString("EnablePluginDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automatically apply alignment formatting when saving files.
        /// </summary>
        internal static string FormatOnSaveDescription {
            get {
                return ResourceManager.GetString("FormatOnSaveDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Format On Save.
        /// </summary>
        internal static string FormatOnSaveDisplayName {
            get {
                return ResourceManager.GetString("FormatOnSaveDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum number of spaces to add for alignment. Prevents excessive spacing when variable names differ greatly in length..
        /// </summary>
        internal static string MaxAlignmentGapDescription {
            get {
                return ResourceManager.GetString("MaxAlignmentGapDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max Alignment Gap.
        /// </summary>
        internal static string MaxAlignmentGapDisplayName {
            get {
                return ResourceManager.GetString("MaxAlignmentGapDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum file size to process. Files larger than this will not be formatted..
        /// </summary>
        internal static string MaxFileSizeDescription {
            get {
                return ResourceManager.GetString("MaxFileSizeDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max File Size (bytes).
        /// </summary>
        internal static string MaxFileSizeDisplayName {
            get {
                return ResourceManager.GetString("MaxFileSizeDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimum number of method parameters required before aligning them on separate lines..
        /// </summary>
        internal static string MethodThresholdDescription {
            get {
                return ResourceManager.GetString("MethodThresholdDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Method Parameter Threshold.
        /// </summary>
        internal static string MethodThresholdDisplayName {
            get {
                return ResourceManager.GetString("MethodThresholdDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code Align.
        /// </summary>
        internal static string OptionsCategoryName {
            get {
                return ResourceManager.GetString("OptionsCategoryName", resourceCulture);
            }
        }
    }
}
